all: True
dir: "mocks/"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
with-expecter: True
packages:
  github.com/nh3000-org/maroto/v2:
    config:
      recursive: True